### ISSUE TITLE
Docker containers in CI

### ISSUE THREAD

**Issue by c71n93** [CoolStory-Studio/coolstory-gram-server#7]
In terms of CI run efficiency it is better to use docker container with all installed dependencies.

Tasks:
- To create Dockerfiles for each OS and save these Dockerfiles in the `docker` folder
- To create docker images from this Dockerfiles.
- To create organization account on DockerHub and upload docker images.
- To make it possible to buid our project inside docker container.
- Edit github workflows so that it can build project inside this docker container.

@temikfart @cadnev WDYT?

**Comment by cann3v** [comment]
The `Dockerfile` should contain instructions for installing CMake and Boost, right?

**Comment by temikfart** [comment]
> The `Dockerfile` should contain instructions for installing CMake and Boost, right?

We want to create two `Dockerfile`s:
1. One `Dockerfile` for each OS (ubuntu, windows) with only installed Boost library;
2. One `Dockerfile` to copy project into container (as Base Image use `Dockerfile` from p.1) and build it using CMake.
